In [1]:
import numpy as np
import pandas as pd

In [68]:
df = pd.read_csv('eeg_feature_dataset.csv')
df

,SpectralCentroid,SpectralSpread,SpectralEntropy,PeakFrequency,PeakPower,MeanFrequency,MedianFrequency,DeltaPower,ThetaPower,AlphaPower,BetaPower,GammaPower,RelDeltaPower,RelThetaPower,RelAlphaPower,RelBetaPower,RelGammaPower,MeanAmplitude,StdAmplitude,Label
0,9.451415,7.068857,5.537412,3.47220,345.633650,9.451415,7.98606,1362.894854,959.303770,1258.051060,1042.239694,17.281865,0.293742,0.206757,0.271145,0.224632,0.003725,9.716287,43.096822,0.0
1,10.288984,7.073756,5.666750,2.08332,251.941591,10.288984,9.02772,926.584640,962.782522,1056.302034,1310.415018,26.383085,0.216367,0.224820,0.246657,0.305995,0.006161,-0.048457,40.873679,0.0
2,8.853437,6.969847,5.394722,1.38888,600.034952,8.853437,7.98606,2007.651939,785.192537,888.198920,1872.819609,25.287950,0.359849,0.140737,0.159200,0.335682,0.004533,-3.328816,44.045009,0.0
3,7.924760,7.857801,5.001348,0.69444,714.279497,7.924760,4.86108,1727.737771,550.876078,854.408238,776.384189,13.785471,0.440391,0.140415,0.217784,0.197896,0.003514,1.842753,41.324710,0.0
4,5.634715,6.201117,4.679839,0.69444,2313.490263,5.634715,2.77776,5649.888977,1926.483632,1202.315759,1156.732745,21.718959,0.567421,0.193478,0.120749,0.116171,0.002181,2.193733,57.193504,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,5.749752,4.888274,4.859762,1.38888,12436.946308,5.749752,3.81942,37617.374831,15138.923437,15203.902145,6157.344706,77.413988,0.507007,0.204042,0.204918,0.082989,0.001043,-2.904146,150.708922,2.0
3996,6.357023,4.338344,4.956389,2.08332,11114.654067,6.357023,5.20830,25930.876428,31909.350543,16067.755065,5934.390890,68.852946,0.324496,0.399310,0.201070,0.074262,0.000862,4.812244,172.516826,2.0
3997,6.586625,4.848929,5.120297,2.08332,9189.255860,6.586625,5.20830,29789.040901,25019.293499,15959.384831,7512.790264,154.048813,0.379795,0.318983,0.203474,0.095784,0.001964,-3.682401,164.618604,2.0
3998,6.002199,4.396611,4.947477,2.43054,7497.065735,6.002199,4.86108,39231.564742,24875.336245,15296.050559,5893.245658,106.445354,0.459372,0.291271,0.179105,0.069005,0.001246,0.497253,172.334079,2.0
3999,6.871808,5.299363,5.040767,1.38888,8758.595411,6.871808,5.90274,24851.010897,28173.660393,16259.491841,9789.080007,122.285637,0.313793,0.355748,0.205308,0.123606,0.001544,7.271579,162.048894,2.0

In [69]:
X = df.drop('Label',axis=1)
y = df['Label']

In [70]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
pca = PCA()
X_pca = pca.fit_transform(X_scaled)

In [71]:
pca = PCA(n_components=0.95)
X_reduced = pca.fit_transform(X_scaled)

In [72]:
num_components = X_reduced.shape[1]
pca_columns = [f'PC{i+1}' for i in range(num_components)]
X_reduced_df = pd.DataFrame(X_reduced, columns=pca_columns)

In [73]:
df_pca = X_reduced_df
df_pca = df_pca.join(y)

In [74]:
df_pca

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,Label
0,1.668208,-1.856604,0.573940,0.585986,0.880840,-0.504632,0.339774,0.600314,-0.409244,-0.309249,0.0
1,2.331738,-2.147647,0.890178,1.170292,0.059311,-0.443430,0.177878,0.412710,-0.274302,-0.412057,0.0
2,1.417193,-1.829635,1.359724,0.783879,-0.235022,-0.305320,0.219117,0.130189,-0.848085,-0.281839,0.0
3,0.403883,-1.541546,1.322419,0.580306,0.197224,-0.787777,-0.126030,0.423613,-0.696019,-0.622715,0.0
4,-1.250401,-0.582929,1.063771,0.373096,0.233605,-0.311240,-0.056566,0.368625,-0.435432,-0.240268,0.0
...,...,...,...,...,...,...,...,...,...,...,...
3995,-0.879436,0.293894,0.500845,-0.168950,-0.286465,-0.571454,0.284567,0.727023,-0.087708,-0.043735,2.0
3996,-0.354463,0.553864,-0.409763,0.528646,0.448074,-0.084742,0.595804,1.033082,0.257000,-0.130345,2.0
3997,-0.113209,0.233644,0.167482,0.428078,-0.318464,-0.241375,0.389384,0.957375,0.211261,-0.017811,2.0
3998,-0.639573,0.478088,0.137040,0.063022,0.021986,-0.256948,0.509675,0.790321,0.238575,0.132371,2.0
3999,0.159772,0.179799,0.082181,0.597432,0.664761,-0.223764,0.510263,1.004772,0.063983,-0.319653,2.0

In [75]:
from sklearn.feature_selection import SelectKBest, f_classif
selector = SelectKBest(score_func=f_classif, k=50)
X_new = selector.fit_transform(X, y)
selected_features = X.columns[selector.get_support()]
X_top50 = pd.DataFrame(X_new, columns=selected_features)

/home/amogh-asus/miniconda3/envs/cuda_env/lib/python3.12/site-packages/sklearn/feature_selection/_univariate_selection.py:783: UserWarning: k=50 is greater than n_features=19. All the features will be returned.
  warnings.warn(

In [76]:
df_pca_50 = X_top50
df_pca_50 = df_pca_50.join(y)
df_pca_50

,SpectralCentroid,SpectralSpread,SpectralEntropy,PeakFrequency,PeakPower,MeanFrequency,MedianFrequency,DeltaPower,ThetaPower,AlphaPower,BetaPower,GammaPower,RelDeltaPower,RelThetaPower,RelAlphaPower,RelBetaPower,RelGammaPower,MeanAmplitude,StdAmplitude,Label
0,9.451415,7.068857,5.537412,3.47220,345.633650,9.451415,7.98606,1362.894854,959.303770,1258.051060,1042.239694,17.281865,0.293742,0.206757,0.271145,0.224632,0.003725,9.716287,43.096822,0.0
1,10.288984,7.073756,5.666750,2.08332,251.941591,10.288984,9.02772,926.584640,962.782522,1056.302034,1310.415018,26.383085,0.216367,0.224820,0.246657,0.305995,0.006161,-0.048457,40.873679,0.0
2,8.853437,6.969847,5.394722,1.38888,600.034952,8.853437,7.98606,2007.651939,785.192537,888.198920,1872.819609,25.287950,0.359849,0.140737,0.159200,0.335682,0.004533,-3.328816,44.045009,0.0
3,7.924760,7.857801,5.001348,0.69444,714.279497,7.924760,4.86108,1727.737771,550.876078,854.408238,776.384189,13.785471,0.440391,0.140415,0.217784,0.197896,0.003514,1.842753,41.324710,0.0
4,5.634715,6.201117,4.679839,0.69444,2313.490263,5.634715,2.77776,5649.888977,1926.483632,1202.315759,1156.732745,21.718959,0.567421,0.193478,0.120749,0.116171,0.002181,2.193733,57.193504,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,5.749752,4.888274,4.859762,1.38888,12436.946308,5.749752,3.81942,37617.374831,15138.923437,15203.902145,6157.344706,77.413988,0.507007,0.204042,0.204918,0.082989,0.001043,-2.904146,150.708922,2.0
3996,6.357023,4.338344,4.956389,2.08332,11114.654067,6.357023,5.20830,25930.876428,31909.350543,16067.755065,5934.390890,68.852946,0.324496,0.399310,0.201070,0.074262,0.000862,4.812244,172.516826,2.0
3997,6.586625,4.848929,5.120297,2.08332,9189.255860,6.586625,5.20830,29789.040901,25019.293499,15959.384831,7512.790264,154.048813,0.379795,0.318983,0.203474,0.095784,0.001964,-3.682401,164.618604,2.0
3998,6.002199,4.396611,4.947477,2.43054,7497.065735,6.002199,4.86108,39231.564742,24875.336245,15296.050559,5893.245658,106.445354,0.459372,0.291271,0.179105,0.069005,0.001246,0.497253,172.334079,2.0
3999,6.871808,5.299363,5.040767,1.38888,8758.595411,6.871808,5.90274,24851.010897,28173.660393,16259.491841,9789.080007,122.285637,0.313793,0.355748,0.205308,0.123606,0.001544,7.271579,162.048894,2.0

In [77]:
from sklearn.model_selection import train_test_split
X_pca = df_pca_50.drop('Label',axis=1)
Y_pca = df_pca_50['Label']
X_train, X_test, y_train, y_test = train_test_split(
    X_pca, Y_pca, test_size=0.2, random_state=42
)

In [78]:
from collections import Counter
print("Before oversampling:", Counter(y_train))

Before oversampling: Counter({1.0: 1302, 0.0: 1252, 2.0: 646})

In [79]:
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state=42)
X_train_res, y_train_res = rus.fit_resample(X_train, y_train)
print("After undersampling:", Counter(y_train_res))

After undersampling: Counter({0.0: 646, 1.0: 646, 2.0: 646})

In [80]:
from imblearn.over_sampling import KMeansSMOTE, ADASYN
smote = KMeansSMOTE(sampling_strategy={1:2000},k_neighbors=5,random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)
print("After SMOTE:", Counter(y_train_smote))

After SMOTE: Counter({1.0: 2000, 0.0: 1252, 2.0: 646})

In [44]:
from imblearn.over_sampling import ADASYN
adasyn = ADASYN(sampling_strategy={1: 2000}, n_neighbors=5, random_state=42)
X_train_adasyn, y_train_adasyn = adasyn.fit_resample(X_train, y_train)
print("After ADASYN:", Counter(y_train_adasyn))

After ADASYN: Counter({1.0: 1950, 0.0: 1252, 2.0: 646})

In [45]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

estimators1 = [
    ('rf', RandomForestClassifier(n_estimators=10, random_state=42)),
    ('gb', GradientBoostingClassifier(n_estimators=10, random_state=42)),
    ('svc', SVC(probability=True, random_state=42)),
    ('xgb',XGBClassifier(n_estimators=100,learning_rate=0.3))
]

final_estimator1 = GradientBoostingClassifier()
stacking_clf1 = StackingClassifier(
    estimators=estimators1,
    final_estimator=final_estimator1,
    cv=10
)
stacking_clf1.fit(X_train_smote, y_train_smote)
y_pred1 = stacking_clf1.predict(X_test)
print("Stacking Accuracy(With SMOTE):", accuracy_score(y_test, y_pred1))
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred1))

Stacking Accuracy(With SMOTE): 0.9525
              precision    recall  f1-score   support

         0.0       0.96      0.96      0.96       348
         1.0       0.93      0.95      0.94       298
         2.0       0.97      0.95      0.96       154

    accuracy                           0.95       800
   macro avg       0.96      0.95      0.95       800
weighted avg       0.95      0.95      0.95       800

In [46]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

estimators2 = [
    ('rf', RandomForestClassifier(n_estimators=10, random_state=42)),
    ('gb', GradientBoostingClassifier(n_estimators=10, random_state=42)),
    ('xgb',XGBClassifier(n_estimators=100,learning_rate=0.3)),
    ('svc', SVC(probability=True, random_state=42)),
]

final_estimator2 = GradientBoostingClassifier()
stacking_clf2 = StackingClassifier(
    estimators=estimators2,
    final_estimator=final_estimator2,
    cv=10
)
stacking_clf2.fit(X_train_adasyn, y_train_adasyn)
y_pred2 = stacking_clf2.predict(X_test)
print("Stacking Accuracy(With ADASYN):", accuracy_score(y_test, y_pred2))
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred2))

Stacking Accuracy(With ADASYN): 0.9525
              precision    recall  f1-score   support

         0.0       0.97      0.95      0.96       348
         1.0       0.93      0.95      0.94       298
         2.0       0.97      0.95      0.96       154

    accuracy                           0.95       800
   macro avg       0.96      0.95      0.95       800
weighted avg       0.95      0.95      0.95       800

In [51]:
estimators3 = [
    ('rf', RandomForestClassifier(n_estimators=10, random_state=42)),
    ('gb', GradientBoostingClassifier(n_estimators=10, random_state=42)),
    ('svc', SVC(probability=True, random_state=42)),
    ('xgb',XGBClassifier(n_estimators=100,learning_rate=0.3))
]

final_estimator3 = GradientBoostingClassifier()
stacking_clf3 = StackingClassifier(
    estimators=estimators3,
    final_estimator=final_estimator3,
    cv=10
)
stacking_clf3.fit(X_train_res, y_train_res)
y_pred3 = stacking_clf3.predict(X_test)
print("Stacking Accuracy(With Undersampling):", accuracy_score(y_test, y_pred3))
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred3))

Stacking Accuracy(With Undersampling): 0.94625
              precision    recall  f1-score   support

         0.0       0.96      0.95      0.95       348
         1.0       0.92      0.94      0.93       298
         2.0       0.96      0.96      0.96       154

    accuracy                           0.95       800
   macro avg       0.95      0.95      0.95       800
weighted avg       0.95      0.95      0.95       800